services:
  web:
    build: .
    command: gunicorn skilltrack.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app:cached
      - staticfiles_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  staticfiles_volume: